apiVersion: v1
kind: Secret
metadata:
  name: ride-share-mysql-secrets
  namespace: ride-share
type: Opaque
data:
  DB_PASSWORD: cm9vdF9wYXNzd29yZAo=

---

apiVersion: v1
kind: Secret
metadata:
  name: ride-share-mongodb-secrets
  namespace: ride-share
type: Opaque
data:
  MONGO_PASSWORD: YWRtaW5wYXNzd29yZAo=