pipeline any {
      agent any

      environment {
            NAMESPACE = 'ride-share'
            K8S_DIR = 'kubernetes'
      }
      stages {
            stage('checkout') {
                  steps {
                        checkout scm
                  }
            }
            stage('connect Docker to Minikube') {
                  steps {
                        sh 'eval $(minikube docker-env) && docker info'
                  }
            }
            stage('Build Images'){
                  steps {
                        sh '''
                        kubectl apply -f ${K8S_DIR}/namespaces.yaml
                        kubectl apply -f ${K8S_DIR}/configmaps.yaml
                        kubectl apply -f ${K8S_DIR}/secrets/
                        kubectl apply -f ${K8S_DIR}/services/
                        kubectl apply -f ${K8S_DIR}/pvc/
                        kubectl apply -f ${K8S_DIR}/statefulsets/
                        kubectl apply -f ${K8S_DIR}/deployments/
                        kubectl apply -f ${K8S_DIR}/ingress.yaml
                        '''                        
                  }
            }
            stage('Rollout Restart images'){
                  steps {
                        sh '''
                        kubectl rollout restart deployment api-gateway -n ${NAMESPACE}
                        kubectl rollout restart deployment user-service -n ${NAMESPACE}
                        kubectl rollout restart deployment driver-service -n ${NAMESPACE}
                        kubectl rollout restart deployment booking-service -n ${NAMESPACE}
                        kubectl rollout restart deployment payment-service -n ${NAMESPACE}
                        kubectl rollout restart deployment notification-service -n ${NAMESPACE}
                        kubectl rollout restart deployment frontend -n ${NAMESPACE}                        
                        '''
                  }
            }
            stage('verify rollout'){
                  steps{
                        sh '''
                        kubectl rollout status deployment api-gateway -n ${NAMESPACE} --timeout=90s
                        kubectl rollout status deployment user-service -n ${NAMESPACE} --timeout=90s
                        kubectl rollout status deployment driver-service -n ${NAMESPACE} --timeout=90s
                        kubectl rollout status deployment booking-service -n ${NAMESPACE} --timeout=90s
                        kubectl rollout status deployment payment-service -n ${NAMESPACE} --timeout=90s
                        kubectl rollout status deployment notification-service -n ${NAMESPACE} --timeout=90s
                        kubectl rollout status deployment frontend -n ${NAMESPACE} --timeout=90s
                        '''                      
                  }
            }
            }
      post {
            success {
                  echo 'Pipeline completed'
            }
            failure {
                  echo 'Pipeline failed'
            }
      }
}