apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend
  namespace: ride-share
spec:
  replicas: 1
  selector:
      matchLabels:
        app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ride-share-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4173

