apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: ride-share
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: ride-share-payment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: ride-share-platform
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: ride-share-platform
                  key: MONGO_PORT
            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: ride-share-platform
                  key: MONGO_DB_NAME
            - name: MONGO_USER
              value: "admin"
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ride-share-mongodb-secrets
                  key: MONGO_PASSWORD
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 5
