apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: ride-share
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: ride-share
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: ride-share
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
